# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ChangelogGenerator < Formula
  desc "Changelog Generator"
  homepage "https://github.com/x-ethr/changelog-generator"
  version "0.1.2"
  license "BSD 3-Clause License"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/x-ethr/changelog-generator/releases/download/v0.1.2/changelog-generator-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "9a89ebb70331ca4463b812e712df1e11b3bb3cb4fdcbe9e774ae3669a306dd35"

      def install
        bin.install "changelog-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/changelog-generator/releases/download/v0.1.2/changelog-generator-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "518505538890363544d2c570358f2a2470d3ad930ef78a1c505717d29f9d8b24"

      def install
        bin.install "changelog-generator"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-ethr/changelog-generator/releases/download/v0.1.2/changelog-generator-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "d33405cb3dba2836c8a42fae276c3b962e6f6d9cce783bc71970d16da41c0a51"

      def install
        bin.install "changelog-generator"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/changelog-generator/releases/download/v0.1.2/changelog-generator-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "a126e84c98b15ec9c19d373b89850caefd40e71bc254f76cb3d02f931afe66c1"

      def install
        bin.install "changelog-generator"
      end
    end
  end

  conflicts_with "changelog-generator"
end
