# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EthrCli < Formula
  desc "ETHR Utilities CLI"
  homepage "https://github.com/x-ethr/ethr-cli"
  version "0.1.8"
  license "BSD 3-Clause License"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.1.8/ethr-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "fd80a63b71a91580782de8bb874cbd47c714551d109cb7070c0d7f6079096004"

      def install
        bin.install "ethr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.1.8/ethr-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "523786f70163ff8fd31e60d1b537693e8f2af595d641c38524851a71ac34cccc"

      def install
        bin.install "ethr-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.1.8/ethr-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "3002fc458baabff7e9f089130c9646d1a398fa96d14c4c6ef72785fcb21fc692"

      def install
        bin.install "ethr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.1.8/ethr-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "b2440eb667adbe42078ada3ffc0a6d9ea3f9ef3b7de3667feb4a3525c9b02ee6"

      def install
        bin.install "ethr-cli"
      end
    end
  end

  conflicts_with "ethr-cli"
end
