# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EthrCli < Formula
  desc "ETHR Utilities CLI"
  homepage "https://github.com/x-ethr/ethr-cli"
  version "0.2.17"
  license "BSD 3-Clause License"

  depends_on "bash" => :optional
  depends_on "fish" => :optional
  depends_on "git"
  depends_on "zsh" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.2.17/ethr-cli-darwin-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "ca470fbc6772330cac2280875639ca51928cf346c620cee48c8cef1401b64aa7"

      def install
        bin.install "ethr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.2.17/ethr-cli-darwin-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "6710b4ca24d2d32884beace5c9d6300296c7b9aaf01986c0d9e93015e95990d2"

      def install
        bin.install "ethr-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.2.17/ethr-cli-linux-arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2e6350331829b4b31c0b073a9621b1742012cb072ca21757ab6625985024dfd7"

      def install
        bin.install "ethr-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/x-ethr/ethr-cli/releases/download/v0.2.17/ethr-cli-linux-x86-64.tar.gz", using: CurlDownloadStrategy
      sha256 "5d82d7249e75f49da90a46bb7befc47cbaec02b49c3057f4664b7ceab96dfef3"

      def install
        bin.install "ethr-cli"
      end
    end
  end

  conflicts_with "ethr-cli"
end
